**step1: create a dataframe**


- we will create a datafream  using list
- we will create a datafream using dictonary

In [7]:
import pandas as pd 


In [9]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [10]:
type(d1)

pandas.core.frame.DataFrame

step:2

In [11]:
names="mohan","shohan","Rohan","mohot"
pd.DataFrame(names)

0
0   mohan
1  shohan
2   Rohan
3   mohot

In [12]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
data=zip(names,age)
pd.DataFrame(data)

0   1
0   mohan  20
1  shohan  21
2   Rohan  25

In [1]:
import pandas as pd
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
pd.DataFrame(zip(names,age))

0   1
0   mohan  20
1  shohan  21
2   Rohan  25

In [14]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data= zip(names, age,city)
pd.DataFrame(data)

0   1    2
0   mohan  20   mp
1  shohan  21   up
2   Rohan  25  hdr

step3: provide columns

In [15]:
names=["mohan","shohan","Rohan","mohot"]
pd.DataFrame(names,columns=["name"])

name
0   mohan
1  shohan
2   Rohan
3   mohot

In [16]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data=zip(names,age,city)

pd.DataFrame(data,columns=["name","age","city"])

name  age city
0   mohan   20   mp
1  shohan   21   up
2   Rohan   25  hdr

In [2]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
pd.DataFrame(zip(names,age,city),columns=["name","age","city"])

name  age city
0   mohan   20   mp
1  shohan   21   up
2   Rohan   25  hdr

In [20]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data=zip(names,age,city)
columns=["name","age","city"]

pd.DataFrame(data,columns=columns)

name  age city
0   mohan   20   mp
1  shohan   21   up
2   Rohan   25  hdr

In [23]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data=zip(names,age,city)

pd.DataFrame(data,index=[1,2,3],columns=["name","age","city"])

name  age city
1   mohan   20   mp
2  shohan   21   up
3   Rohan   25  hdr

In [25]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data=zip(names,age,city)
columns=["name","age","city"]
indx=["A","B","C"]

pd.DataFrame(data,columns=columns,index=indx)

name  age city
A   mohan   20   mp
B  shohan   21   up
C   Rohan   25  hdr

In [29]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data=zip(names,age)
columns=["name","age"]


pd.DataFrame(data,columns=columns,index=city)

name  age
mp    mohan   20
up   shohan   21
hdr   Rohan   25

In [31]:
names=["mohan","shohan","Rohan","mohot"]
age=[20,21,25]
city=["mp","up","hdr"]
data=zip(names,age,city)
columns=["name","age","city"]
indx=["A","B","C"]

df=pd.DataFrame(data,columns=columns,index=indx)

In [32]:
df

name  age city
A   mohan   20   mp
B  shohan   21   up
C   Rohan   25  hdr

In [2]:
import pandas as pd
names=["mrityunjay","pankaj","prabin","dhanjay"]
age=[24,23,23.5,25]
data=zip(names,age)

pd.DataFrame(data,columns=["names","age"])

names   age
0  mrityunjay  24.0
1      pankaj  23.0
2      prabin  23.5
3     dhanjay  25.0

**step5 add new column on existing data fram**

In [13]:
import pandas as pd
names=["mrityunjay","pankaj","prabin","dhanjay"]
age=[24,23,23.5,25]
city=["hdr","blr","pune","nagpur"]
d=zip(names,age,city)
col=[1,2,3]
index=["A","B","C","D"]
df=pd.DataFrame(d,columns=col,index=index)
df

1     2       3
A  mrityunjay  24.0     hdr
B      pankaj  23.0     blr
C      prabin  23.5    pune
D     dhanjay  25.0  nagpur

In [ ]:
- if we want to add a new columns
- check how many row
- for ex in above df have three column 
- we should new column 
- i want to add new column  : *salary*
- make list with 3  value 
salary=[10000,20000,30000]
syntax: df[columns]=[10000,200000,30000]= list of value
salary=[10000,200000,3000]
df["salary"]=salary


In [15]:
salary=[10000,20000,30000,4000]
df["salary"]=salary
df

1     2       3  salary
A  mrityunjay  24.0     hdr   10000
B      pankaj  23.0     blr   20000
C      prabin  23.5    pune   30000
D     dhanjay  25.0  nagpur    4000

In [ ]:
use case -1 :
- create empaty data frame  first
- create 3 list using list compreinsion
- l1= a value from 1 to 10
-l2 =square of 1 to 10
-l3 =cube of 1 to 10
-finaly make a data frame

In [43]:
import pandas as pd
df1=pd.DataFrame()
l1=[i for i in range(1,11)]
l2=[i**2 for i in range(1,11)]
l3=[i**3 for i in range(1,11)]
col=["number","sqare","cube"]
indx=[1,2,3]
df1["x"]=l1
df1["y"]=l2
df1["z"]=l3

df2=df1
df2

x    y     z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [60]:
df2.drop([4,8])

TypeError: 'DataFrame' object is not callable

In [ ]:
step-6
update already exist colmns


- create a new col
    - create new list
    - df[" s"]
- update existing column are same way only
    - here also we need a make a list of value =num of row
    - while updating the existing column
    - we nee d to provide already existing name 
-  df[""]= list of vlue

In [44]:
l4=[i**4 for i in range(1,11)]
df2["z"]=l4
df2

x    y      z
0   1    1      1
1   2    4     16
2   3    9     81
3   4   16    256
4   5   25    625
5   6   36   1296
6   7   49   2401
7   8   64   4096
8   9   81   6561
9  10  100  10000

In [ ]:
step7: Drop the columns

In [36]:
#how to check columns
df1.columns

Index(['name', 'age', 'city', 'salary', 'degree', 'goal'], dtype='object')

In [ ]:
- if younwabt to drop  specific colmns 
- we will drop meathod 
- we already know about difference between keywards and meathods
- keywards will use directly
- method will use crossponding dataframe 
- mathod name : drop


In [ ]:
df1.drop()
* which col we want to drop 
- axis represent the spesfic value is a row or column
    axis - 0 means row 
    axis- 1 means 1
- inplace:will provide overwrite the dataframe or not 
    -inplace = True , this indicates overwrite the dataframe
    - inplace= False, this indicates the modifi dataframe will be use when provide 


In [51]:
df1.drop("x")

KeyError: "['x'] not found in axis"

In [37]:
df_new=df2.drop("x",axis=1)
df_new1=d2.drop("y",axis=1)
df_new
df_new1

NameError: name 'df2' is not defined

In [34]:
df_new=df1.drop("x",axis=1)
df_new1=df1.drop("y",axis=1,)

KeyError: "['x'] not found in axis"

In [24]:
#make a data frame
import pandas as pd
l1=["mrityunjay","pankaj","manish","sahil","santosh"]
l2=[24,23,25,26,23]
l3=["hdr","blr","pune","nagpur","patna"]
data=zip(l1,l2,l3)
pd.DataFrame(l1,columns=["l2"],index=l3)
#df=pd.DataFrame(data,columns=["name","age","city"],index=["A","B","C","D","E"])


l2
hdr     mrityunjay
blr         pankaj
pune        manish
nagpur       sahil
patna      santosh

In [26]:
#update dataframe
df["salary"]=[25000,30000,15000,34000,43000]
df1=df
df1

name  age    city  salary
A  mrityunjay   24     hdr   25000
B      pankaj   23     blr   30000
C      manish   25    pune   15000
D       sahil   26  nagpur   34000
E     santosh   23   patna   43000

In [31]:
degree=["BBA","BE","BA","MBBS","Nursing"]
goal=["BM","ER","IAS","DR","DR"]
df1["degree"]=degree
df1["goal"]=goal
df1

name  age    city  salary   degree goal
A  mrityunjay   24     hdr   25000      BBA   BM
B      pankaj   23     blr   30000       BE   ER
C      manish   25    pune   15000       BA  IAS
D       sahil   26  nagpur   34000     MBBS   DR
E     santosh   23   patna   43000  Nursing   DR

- Length of values
- length of index

In [43]:
#drop the columns and row 
df1.drop("E",axis=0)

name  age    city  salary degree goal
A  mrityunjay   24     hdr   25000    BBA   BM
B      pankaj   23     blr   30000     BE   ER
C      manish   25    pune   15000     BA  IAS
D       sahil   26  nagpur   34000   MBBS   DR

In [64]:
import pandas as pd
l1=["mrityunjay","pankaj","manish","sahil","santosh"]
l2=[24,23,25,26,23]
l3=["hdr","blr","pune","nagpur","patna"]
data=zip(l1,l2,l3)
df=pd.DataFrame(data,columns=["name","age","city"],index=["A","B","C","D","E"])
df["degree"]=degree
df.drop("age",axis=1)
df.drop("D",axis=0)

name  age   city   degree
A  mrityunjay   24    hdr      BBA
B      pankaj   23    blr       BE
C      manish   25   pune       BA
E     santosh   23  patna  Nursing

In [ ]:
states=["hydrabad","bangaloru","channei","maharastra","madhaypredesh","bihar","utter pradesh","hrayana","uttrakhand"]
population=[20,23,35,42,22,12,]

**step8**
- drop the row
- drop the row and column both are smame
-  only differencre is axis
-  axix =0  row
-  by defult axis =0 avilable
-  which means if provide any value , it will represent  

In [14]:
import pandas as pd
l1=["mrityunjay","pankaj","manish","sahil","santosh"]
l2=[24,23,25,26,23]
l3=["hdr","blr","pune","nagpur","patna"]
data=zip(l1,l2,l3)
df=pd.DataFrame(data,columns=["name","age","city"],index=["A","B","C","D","E"])
#df["degree"]=degree
df.drop("age",axis=1)
df.drop(["A","D"])

name  age   city
B   pankaj   23    blr
C   manish   25   pune
E  santosh   23  patna

In [5]:
import pandas as pd
df1=pd.DataFrame()
l1=[i for i in range(1,11)]
l2=[i**2 for i in range(1,11)]
l3=[i**3 for i in range(1,11)]
col=["number","sqare","cube"]
indx=[1,2,3]
df1["x"]=l1
df1["y"]=l2
df1["z"]=l3

df2=df1
df2

x    y     z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [7]:
df2.drop(4)

x    y     z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [12]:
# multipule rows and multipule columns 
df2.drop([4,8])

x    y     z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
5   6   36   216
6   7   49   343
7   8   64   512
9  10  100  1000

In [13]:
 df2.drop(["x","y"], axis=1)

z
0     1
1     8
2    27
3    64
4   125
5   216
6   343
7   512
8   729
9  1000

In [21]:
df2.drop([0,2],axis=1)
# [0,1] index
# axis = 1, columns
# error

KeyError: '[0, 2] not found in axis'

###  how to select the columns 

In [23]:
df2

x    y     z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [27]:
df2["x"]

# srise
# no columns name display
#whenever you see this type : srise type 

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: x, dtype: int64

In [29]:
type(df2["x"])

pandas.core.series.Series

In [26]:
df2[["x"]]

x
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [32]:
type(df2[["x"]])

pandas.core.frame.DataFrame

In [67]:
df2["x","y"]

KeyError: ('x', 'y')

In [35]:
df2.x

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: x, dtype: int64

In [36]:
type(df2.x)

pandas.core.series.Series

In [68]:
df

name  age    city
A  mrityunjay   24     hdr
B      pankaj   23     blr
C      manish   25    pune
D       sahil   26  nagpur
E     santosh   23   patna

In [39]:
df2[["x","y"]]

x    y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [43]:
df2["x"].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

- all values comes in an array 
- array means itnis a listnof element only represent using numpy package
- generaly element present in 4 ways
- list: basic represent
- numpy array : Array with numpy
- tensor: tensorflow package
- torch: pythorch package

In [45]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [46]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [56]:
list1=[1,2,3,4,5,6]
list2=[10,20,34,45,50,51]
list1+list2

[1, 2, 3, 4, 5, 6, 10, 20, 34, 45, 50, 51]

In [57]:
l1=np.array(list1)
l1

array([1, 2, 3, 4, 5, 6])

In [58]:
l2=np.array(list2)
l2

array([10, 20, 34, 45, 50, 51])

In [59]:
l1=np.array(list1)
l2=np.array(list2)
l1 + l2

array([11, 22, 37, 49, 55, 57])

In [ ]:
#read numpy 
# 

In [63]:
df2["x"].values

#imzine when we work on ml problem 
# we got some series of values 
# with  that serises of value also we can create a dataframe 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [66]:
df2["NUMBER"]=df2["x"].values
df2

x    y     z  NUMBER
0   1    1     1       1
1   2    4     8       2
2   3    9    27       3
3   4   16    64       4
4   5   25   125       5
5   6   36   216       6
6   7   49   343       7
7   8   64   512       8
8   9   81   729       9
9  10  100  1000      10

**stap 10**
**save the dataframe**

- DataFrame we can save in two formate
        - csv 
        - xlsx
- in order to save any data
          - where you want to save : directory name
          - what is the file name of the file name for storing
          - what is the exintation
  
-  we already seen same in file handling

In [ ]:
#case1: saving file in same location
#No need to provide directory name 
#directiry givr obnly name of 

In [70]:
#Data frame name : df2
df2.to_csv("data.csv")
df2.to_excel("data.xlsx")

In [ ]:
df.

**step=11**
#how to read the data frame 

In [71]:
import pandas as pd
pd.read_csv("data.csv")

Unnamed: 0   x    y     z  NUMBER
0           0   1    1     1       1
1           1   2    4     8       2
2           2   3    9    27       3
3           3   4   16    64       4
4           4   5   25   125       5
5           5   6   36   216       6
6           6   7   49   343       7
7           7   8   64   512       8
8           8   9   81   729       9
9           9  10  100  1000      10

In [73]:
import pandas as pd
pd.read_excel("data.xlsx")

Unnamed: 0   x    y     z  NUMBER
0           0   1    1     1       1
1           1   2    4     8       2
2           2   3    9    27       3
3           3   4   16    64       4
4           4   5   25   125       5
5           5   6   36   216       6
6           6   7   49   343       7
7           7   8   64   512       8
8           8   9   81   729       9
9           9  10  100  1000      10

**step-12**
#how to aviod index columns 
### while we save the daataframe
### automaticaly a new column will create 
### that we need to avoid 
### premmission error means close the data file from laptop


In [77]:
df2.to_csv("data.csv",index=False)
df2.to_excel("data.xlsx",index=False)

In [79]:
import pandas as pd
pd.read_excel("data.xlsx")

x    y     z  NUMBER
0   1    1     1       1
1   2    4     8       2
2   3    9    27       3
3   4   16    64       4
4   5   25   125       5
5   6   36   216       6
6   7   49   343       7
7   8   64   512       8
8   9   81   729       9
9  10  100  1000      10

In [80]:
pip show numpy


Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR