In [1]:
#import numpy package 
import numpy as np
list=[[10,20,30,40],[4,54,76,12]]
ny=np.array(list)
print(ny)


[[10 20 30 40]
 [ 4 54 76 12]]


In [4]:
# numpy array type #use list

import numpy as np
list=[[10,20,30,40],[4,54,76,12]]
ny=np.array(list)

print(type(ny))

<class 'numpy.ndarray'>


In [ ]:
# nidm
import numpy as np
list=[[10,20,30,40],[4,54,76,12]]
ny=np.array(list)
print(ny.ndim)


In [5]:
# numpy array type #use tuple
#array type , nidm

import numpy as np
tuple=[(10,20,30,40),(23,43,53,67,)]
ny=np.array(list)
print(ny)
print(type(ny))
print(ny.ndim)


[[10 20 30 40]
 [ 4 54 76 12]]
<class 'numpy.ndarray'>
2


In [6]:
#slicing numpy array

import numpy as np
list=[10,20,30,40,54,76,12]
ny=np.array(list)

ny[::2]

array([10, 30, 54, 12])

In [11]:
#num in numpy arr
arr1=np.zeros(3)
arr2=np.ones(2)
print(arr1)
print(arr2)

[0. 0. 0.]
[1. 1.]


In [7]:
#numpy array shape

import numpy as np
list2=[[10,23,45],[45,76,78],[54,64,89],[12,34,45]]
ny1=np.array(list2)
print(ny1.shape)


(4, 3)


In [8]:
# T shape array
import numpy as np
list2=[[10,23,45],[45,76,78],[54,64,89],[12,34,45]]
ny1=np.array(list2)
print(ny1.shape)

print(ny1.T)

(4, 3)
[[10 45 54 12]
 [23 76 64 34]
 [45 78 89 45]]


In [12]:
#max 
import numpy as np
list2=[[10,23,45],[45,76,78],[54,64,89],[12,34,45]]
ny1=np.array(list2)
print(ny1)
print(ny1.max())


[[10 23 45]
 [45 76 78]
 [54 64 89]
 [12 34 45]]
89


In [13]:
#min
import numpy as np
list2=[[10,23,45],[45,76,78],[54,64,89],[12,34,45]]
ny1=np.array(list2)
print(ny1)
print(ny1.min())


[[10 23 45]
 [45 76 78]
 [54 64 89]
 [12 34 45]]
10


In [14]:
#sum
import numpy as np
list2=[[10,23,45],[45,76,78],[54,64,89],[12,34,45]]
ny1=np.array(list2)
print(ny1)
print(ny.sum())


[[10 23 45]
 [45 76 78]
 [54 64 89]
 [12 34 45]]
242


In [18]:
#reshape arr
import numpy as np
list2=[[10,23,45],[45,76,78],[54,64,89],[12,34,45]]
ny1=np.array(list2)
print(f"arr:{ny1}")
print(f"arr1:{ny1.reshape(4,3)}")
print(f"arr2:{ny1.reshape(6,2)}")

arr:[[10 23 45]
 [45 76 78]
 [54 64 89]
 [12 34 45]]
arr1:[[10 23 45]
 [45 76 78]
 [54 64 89]
 [12 34 45]]
arr2:[[10 23]
 [45 45]
 [76 78]
 [54 64]
 [89 12]
 [34 45]]


In [45]:
#nonzero count

import numpy as np
list2=[[10,23,0,45],[45,0,76,78],[0,54,64,89],[12,34,45,1]]
ny1=np.array(list2)
print(np.count_nonzero(ny1))

13


In [47]:
#sort numpy arr
import numpy as np
list2=[[10,23,45,40],[45,76,32,78],[54,64,12,89],[12,2,34,45]]
ny1=np.array(list2)
ny1.sort()
ny1

array([[10, 23, 40, 45],
       [32, 45, 76, 78],
       [12, 54, 64, 89],
       [ 2, 12, 34, 45]])

In [68]:
#flatten numpy arr
import numpy as np
list2=[[10,23,45,40],[45,76,32,78],[54,64,12,89],[12,2,34,45]]
ny1=np.array(list2)
print(ny1.flatten())

[10 23 45 40 45 76 32 78 54 64 12 89 12  2 34 45]


In [50]:
#add value 
import numpy as np
list2=[[10,23,45,40],[45,76,32,78],[54,64,12,89],[12,2,34,45]]
ny1=np.array(list2)
print(ny1+2)

[[12 25 47 42]
 [47 78 34 80]
 [56 66 14 91]
 [14  4 36 47]]


In [52]:
#diagonal if matrix
import numpy as np
list2=[[10,23,45,40],[45,76,32,78],[54,64,12,89],[12,2,34,45]]
ny1=np.array(list2)
ny1.diagonal()

array([10, 76, 12, 45])

In [54]:
#trace
import numpy as np
list2=[[10,23,45,40],[45,76,32,78],[54,64,12,89],[12,2,34,45]]
ny1=np.array(list2)
ny1.trace()

143

In [67]:
#adding and subtraction matrix
import numpy as np
matrix1=[[11,23,45],[43,23,45],[67,34,56]]
matrix2=[[76,32,43],[12,43,54],[90,23,54]]
matrix_a=np.array(matrix1)
matrix_b=np.array(matrix2)

np.add(matrix_a,matrix_b)

array([[ 87,  55,  88],
       [ 55,  66,  99],
       [157,  57, 110]])

In [66]:
import numpy as np
matrix1=[[11,23,45],[43,23,45],[67,34,56]]
matrix2=[[76,32,43],[12,43,54],[90,23,54]]
matrix_a=np.array(matrix1)
matrix_b=np.array(matrix2)

np.subtract(matrix_a,matrix_b)

array([[-65,  -9,   2],
       [ 31, -20,  -9],
       [-23,  11,   2]])

In [64]:
#sum
import numpy as np
matrix1=[[11,23,45],[43,23,45],[67,34,56]]
matrix2=[[76,32,43],[12,43,54],[90,23,54]]
matrix_a=np.array(matrix1)
matrix_b=np.array(matrix2)
matrix_a+matrix_b

array([[ 87,  55,  88],
       [ 55,  66,  99],
       [157,  57, 110]])

In [63]:
#subtract
import numpy as np
matrix1=[[11,23,45],[43,23,45],[67,34,56]]
matrix2=[[76,32,43],[12,43,54],[90,23,54]]
matrix_a=np.array(matrix1)
matrix_b=np.array(matrix2)
matrix_a-matrix_b

array([[-65,  -9,   2],
       [ 31, -20,  -9],
       [-23,  11,   2]])